controllers:
    resource: ../src/Controller/
    type: attribute
api_register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: [POST]
api_authenticate:
    path: /api/authenticate
    controller: App\Controller\AuthController::authenticate
api_login_check:
    path: /api/login_check
api_insert:
    path: /api/insert
    controller: App\Controller\BusController::insertBus
api_search:
    path: /api/bus/search
    controller: App\Controller\PassengerController::searchBus
api_book:
    path: /api/bus/book
    controller: App\Controller\PassengerController::bookBus
